# Generated by Django 6.0.1 on 2026-01-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userclick",
            unique_together={("url_shortener", "user_ip")},
        ),
    ]
