# Generated by Django 6.0.2 on 2026-02-11 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortener", "0002_alter_url_created_at"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="url",
            name="url_shorten_short_c_49214d_idx",
        ),
        migrations.AlterField(
            model_name="url",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
